services:
  db:
    image: postgres:latest
    environment:
      - 'POSTGRES_DB=DEV'
      - 'POSTGRES_PASSWORD=0000'
      - 'POSTGRES_USER=nuno'
    ports:
      - "5433:5432"
    restart: always
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    restart: always  # Ensures app container restarts if it fails